
spring:
  application:
    name: MOVIE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_booking
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/